site_name: MkDocs – JetBrains Plugin
site_description: JetBrains plugin providing MkDocs support in all IntelliJ-platform IDEs
site_author: PCSoft

docs_dir: docs
site_dir: ../build/docs

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true

extra:
  version:
    provider: mike
    alias: true

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  language: en
  features:
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Facets:
    - MKDocs: mkdocs-facet.md
    - Angular Material: angular-material-facet.md
  - Configuration (mkdocs.yml): configuration.md
  - IDE Features:
    - Site Page tool window: toolwindow.md
    - Settings: settings.md
  - API Docs: dokka/html/index.html
  - Licences: licences/index.html
